// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRRiwc6-BuFXW6sTagXMZsUO6Kcru0ltw',
    appId: '1:500913682579:web:b3f1829147b256fdfd3566',
    messagingSenderId: '500913682579',
    projectId: 'lotteryapp-7ba43',
    authDomain: 'lotteryapp-7ba43.firebaseapp.com',
    storageBucket: 'lotteryapp-7ba43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKM81RSpFZepezUza03mPi8adlgkGsLA',
    appId: '1:500913682579:android:e433277c15d38e76fd3566',
    messagingSenderId: '500913682579',
    projectId: 'lotteryapp-7ba43',
    storageBucket: 'lotteryapp-7ba43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDka3bgNjQXxrp4vjOwGQhwmqcJWXmaKHo',
    appId: '1:500913682579:ios:844119ffec523ec1fd3566',
    messagingSenderId: '500913682579',
    projectId: 'lotteryapp-7ba43',
    storageBucket: 'lotteryapp-7ba43.firebasestorage.app',
    iosBundleId: 'com.example.lotteryApp',
  );
}
